### ISSUE TITLE
MSK with IAM jar file show SLF4J messages

### ISSUE THREAD

**Issue by lazize** [aws/aws-msk-iam-auth#27]
Hi,

Using kafka package from link below it works fine to connect with MSK. No error or warning message.  
https://kafka.apache.org/quickstart

When I do the same on MSK using IAM jar file from link below I see SLF4J messages below. Kafka command works fine.  
https://docs.aws.amazon.com/msk/latest/developerguide/iam-access-control.html

    $ bin/kafka-console-consumer.sh --bootstrap-server "${KAFKA_BOOTSTRAP_SERVER}" --consumer.config config/iam.properties --topic quickstart-events --from-beginning
    SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation
    SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
    asdasd
    rtyrtyrty

I checked the link it mention above but kafka package already have a jar file.

    $ ls -la libs/slf4j-*
    -rw-r--r-- 1 ec2-user ec2-user 41472 Jan  9  2020 libs/slf4j-api-1.7.30.jar
    -rw-r--r-- 1 ec2-user ec2-user 12211 Jan  9  2020 libs/slf4j-log4j12-1.7.30.jar

    $ ls -lah libs/log4j-1.2.17.jar
    -rw-r--r-- 1 ec2-user ec2-user 479K Jan  6  2020 libs/log4j-1.2.17.jar

    $ ls -la libs/aws-msk-iam-auth-1.0.0-all.jar
    -rw-r--r-- 1 ec2-user ec2-user 6000570 May  5 13:15 libs/aws-msk-iam-auth-1.0.0-all.jar

I tried also with latest version from `aws-msk-iam-auth`, but the messages still show to me.

    $ ls -la libs/aws-msk-iam-auth-1.1.0-all.jar
    -rw-rw-r-- 1 ec2-user ec2-user 12592042 Jun 25 12:48 libs/aws-msk-iam-auth-1.1.0-all.jar

If I remove any (or all) `slf4j` file from libs directory I get the error below.

    $ bin/kafka-topics.sh --bootstrap-server "${KAFKA_BOOTSTRAP_SERVER}" --command-config config/iam.properties --list
    Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
    	at com.typesafe.scalalogging.Logger$.apply(Logger.scala:48)
    	at kafka.utils.Log4jControllerRegistration$.<clinit>(Logging.scala:25)
    	at kafka.admin.TopicCommand$.<clinit>(TopicCommand.scala:49)
    	at kafka.admin.TopicCommand.main(TopicCommand.scala)
    Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    	... 4 more

If I add no-operation (NOP) jar file I get error message about multiple bindings on classpath.

    $ bin/kafka-topics.sh --bootstrap-server "${KAFKA_BOOTSTRAP_SERVER}" --command-config config/iam.properties --list
    SLF4J: Class path contains multiple SLF4J bindings.
    SLF4J: Found binding in [jar:file:/home/ec2-user/kafka_2.13-2.8.0/libs/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: Found binding in [jar:file:/home/ec2-user/kafka_2.13-2.8.0/libs/slf4j-nop-1.7.31.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
    SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
    SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation
    SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
    __amazon_msk_canary
    __amazon_msk_canary_state
    __consumer_offsets
    quickstart-events

If I keep just NOP jar file and remove `slf4j-log4j12-1.7.30.jar`, I still see the same SLF4J messages.

I don't have java skills, so maybe I am doing a mistake.  
But it only happens when I am doing IAM access control.
 
I know it is not an error, but this message annoying me.  
How can I fix this?

**Comment by sayantacC** [comment]
Thanks for reporting this issue. The warning message is generated only when an uber jar is built using `gradle shadowJar` and used with some existing kafka client/tool. 

The warning message is happening because while generating the uber jar we shade and relocate all the dependencies of the library, including slf4j-api. We do this to avoid dependency conflicts with the kafka clients with which the uber jar is being used.

At runtime a class in the uber jar triggers `LoggerFactory` initialization in slf4j-api. At that point slf4j  tries to find a `StaticLoggerBinder` on the classpath. 
Since  slf4j-api has been relocated from `org/slf4j`  to `aws_msk_iam_auth_shadow/org/slf4j`, LoggerFactory starts looking for a `aws_msk_iam_auth_shadow/org/slf4j/impl/StaticLoggerBinder` instead of `org/slf4j/impl/StaticLoggerBinder`. Since we want the uber jar to use the same implementation of slf4j as the existing kafka client, we do not pack a relocated slf4j implementation in it. As no implementation of `aws_msk_iam_auth_shadow/org/slf4j/impl/StaticLoggerBinder` is available on the class path, we see the reported warning.

A few different solutions are possible:
* Not shade slf4j-api and depend on it being present on the class path just as we do for the kafka client libraries.
* Shade slf4j-api but not relocate it. This runs the risk of conflicting with a different version of the slf4j-api being already present.

**Comment by sayantacC** [comment]
The uber jar should not have those unnecessary warnings.
